services:
  morpheus:
    build:
      context: .
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
    image: morpheus-sim
    container_name: morpheus-sim
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: false
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/workspace/Morpheus
    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, graphics]
