ekf:
  ros__parameters:
    #################################################################
    # 基本设置
    #################################################################
    frequency: 50.0
    two_d_mode: true
    publish_tf: true
    print_diagnostics: true
    # debug: true
    # debug_out_file: /tmp/ekf_debug.txt

    #################################################################
    # 坐标系
    #################################################################
    map_frame: map
    odom_frame: odom
    base_link_frame: chassis_link
    world_frame: odom   # Nav2 期望 odom 为“世界系（局部漂移）”

    #################################################################
    # 传感器 1：Gazebo 里程计（nav_msgs/Odometry）
    # 话题来自桥接：
    #   /world/marsyard2022/model/morpheus_rover/odometry
    # 取用 x, y, yaw 与 vx, vy, yaw_rate
    #################################################################
    odom0: /world/marsyard2022/model/morpheus_rover/odometry
    odom0_config: [true,  true,  false,   # x, y, z (只用平面)
                   false, false, true,    # roll, pitch, yaw
                   true,  true,  false,   # vx, vy, vz
                   false, false, true,    # vroll, vpitch, vyaw
                   false, false, false]   # ax, ay, az
    odom0_differential: false
    odom0_relative:     false
    # odom0_queue_size: 10

    #################################################################
    # 传感器 2：IMU（sensor_msgs/Imu）
    # 只用 yaw、yaw rate、线加速度（EKF 积分）
    #################################################################
    imu0: /imu
    imu0_config: [false, false, false,   # 位置 x y z
                  false, false, true,    # 姿态 roll pitch yaw（只用 yaw）
                  false, false, false,   # 线速度
                  false, false, true,    # 角速度（只用 yaw rate）
                  true,  true,  true]    # 线加速度 ax ay az
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    # imu0_queue_size: 50

    #################################################################
    # 其他常用参数（按需微调）
    #################################################################
    sensor_timeout: 0.1
    # transform_time_offset: 0.0
    # reset_on_time_jump: true
