ekf:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: chassis_link
    world_frame: odom   # odom系作为世界系（Nav2 也这么用）

    # 仅用 IMU 先跑通
    imu0: /imu
    imu0_config: [false, false, false,   # x y z 位置（IMU不给）
                  false, false, true,    # roll pitch yaw（只用 yaw）
                  false, false, false,   # x y z 线速度（IMU不给）
                  false, false, true,    # 角速度（用 yaw rate）
                  true,  true,  true]    # 线加速度 ax ay az（EKF会积分）
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

  # 轮里程计（先不启用） 
  # wheel0: /wheel_odom
  # wheel0_config: [true,  true,  false,
  #                 false, false, true,    # x y yaw
  #                 true,  true,  false,   # vx vy
  #                 false, false, false,
  #                 false, false, false]
  # wheel0_differential: true