ekf_odom:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: chassis_link  # morpheus 的主底盘链接名
    world_frame: odom  # 与 Gazebo 模拟环境保持一致

    # 仅用里程计（Gazebo 桥过来的 /odom）
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    # x,y, yaw 用；其余关掉
    odom0_differential: false
    odom0_relative:     false

    # 噪声可按需调，这里给个温和默认
    process_noise_covariance: [0.05, 0,    0,    0,    0,    0,
                               0,    0.05, 0,    0,    0,    0,
                               0,    0,    0.2,  0,    0,    0,
                               0,    0,    0,    0.2,  0,    0,
                               0,    0,    0,    0,    0.2,  0,
                               0,    0,    0,    0,    0,    0.05]
