amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: chassis_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: /scan
    min_particles: 500
    max_particles: 2000
    laser_model_type: likelihood_field
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2
    update_min_d: 0.1
    update_min_a: 0.1
    transform_tolerance: 0.2

bt_navigator:
  ros__parameters:
    use_sim_time: True
    # 建议在 launch 里传 default_bt_xml_filename 的绝对路径，这里留空用默认树

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
 
       # —— 常用/稳妥参数（可跑通；后续再微调）——
      desired_linear_vel: 0.6            # 最大线速度
      max_angular_accel: 2.0             # 角加速度限幅，避免旋转过猛
      lookahead_dist: 0.8                # 基础前瞻距离
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      use_velocity_scaled_lookahead_dist: true
      rotate_to_heading: true            # 允许在起步前对准航向
      rotate_to_heading_angular_vel: 0.8
      allow_reversing: false             # 非差速倒车，先关
      transform_tolerance: 0.2
      use_interpolation: true

      # 避障相关（RPPC特有）
      use_cost_regulated_linear_velocity_scaling: true
      cost_scaling_dist: 0.6
      cost_scaling_gain: 1.0

      # 曲率限幅，防止尖锐转向导致打角过大
      curvature_lookahead_dist: 0.8
      min_curvature: 0.0
      max_curvature: 1.0

    # 小速度阈值，防止微抖
    min_x_velocity_threshold: 0.01


planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.1
      use_astar: true

behavior_server:
  ros__parameters:
    use_sim_time: True

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      w_eucl_dist: 1.0
      w_curvature: 1.0
      w_smoothness: 1.0

waypoint_follower:
  ros__parameters:
    use_sim_time: True

global_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: chassis_link
    update_frequency: 1.0
    publish_frequency: 1.0
    resolution: 0.12          # 原图 0.012207，可略粗以提速
    rolling_window: false
    width: 50.0
    height: 50.0
    robot_radius: 0.41
    footprint: ""
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        inf_is_valid: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6
      cost_scaling_factor: 3.0

local_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: odom
    robot_base_frame: chassis_link
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 10.0
    height: 10.0
    resolution: 0.05
    robot_radius: 0.41
    footprint: ""
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        inf_is_valid: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 3.0

map_server:
  ros__parameters:
    use_sim_time: True
    # yaml_filename 由 bringup_nav2.launch.py 注入；此处留空更稳

lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - map_server
      - amcl
      - controller_server
      - planner_server
      - behavior_server
      - bt_navigator
      - waypoint_follower
      - smoother_server
