amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: chassis_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: /scan
    min_particles: 500
    max_particles: 2000
    laser_model_type: likelihood_field
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2
    update_min_d: 0.1
    update_min_a: 0.1

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.6
      lookahead_dist: 0.8
      rotate_to_heading_angular_vel: 0.8
      allow_reversing: false
      use_velocity_scaled_lookahead_dist: true
      transform_tolerance: 0.2
    min_x_velocity_threshold: 0.01

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.1
      use_astar: true

behavior_server:
  ros__parameters:
    use_sim_time: True

smoother_server:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    use_sim_time: True

global_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: chassis_link
    update_frequency: 1.0
    publish_frequency: 1.0
    resolution: 0.12   # 地图分辨率是0.012207，这里costmap可以取更粗一点，提速
    rolling_window: false
    width: 50.0
    height: 50.0
    robot_radius: 0.41   # ~ sqrt(0.35^2 + 0.21^2)
    plugins: ["obstacle_layer", "inflation_layer", "static_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        inf_is_valid: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6
      cost_scaling_factor: 3.0

local_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: odom
    robot_base_frame: chassis_link
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 10.0
    height: 10.0
    resolution: 0.05
    robot_radius: 0.41
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        inf_is_valid: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 3.0

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "$(find-pkg-share morpheus_nav2)/config/map.yaml"

lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - map_server
      - amcl
      - controller_server
      - planner_server
      - behavior_server
      - bt_navigator
      - waypoint_follower
      - smoother_server
