waypoints:
  - name: "north_east"
    x: 3.0
    y: 6.5
    yaw: 1.57
  - name: "east"
    x: 4.0
    y: 4.0
    yaw: 0.0
  - name: "south_east"
    x: 2.5
    y: 2.0
    yaw: -1.57
  - name: "south"
    x: 0.0
    y: 1.5
    yaw: 3.14
  - name: "south_west"
    x: -2.5
    y: 2.0
    yaw: 1.57
  - name: "west"
    x: -4.0
    y: 4.0
    yaw: 3.14
  - name: "north_west"
    x: -3.0
    y: 6.5
    yaw: 1.57
  - name: "return_home"
    x: 0.0
    y: 4.0
    yaw: 0.0
