teleop_twist_joy:
  ros__parameters:
    use_sim_time: true

    # 输入
    joy_topic: /joy

    # 输出
    cmd_vel_topic: /cmd_vel_joy

    # 摇杆映射（Xbox 常用：左摇杆 1=前后，右摇杆 3=左右）
    axis_linear: 1
    axis_angular: 3

    # 比例 & 双速
    scale_linear: 0.8
    scale_linear_turbo: 1.2
    scale_angular: 1.2
    scale_angular_turbo: 2.0

    # Deadman/加速键（LB / RB）
    enable_button: 4
    enable_turbo_button: 5
    require_enable_button: true
