teleop_twist_joy:
  ros__parameters:
    use_sim_time: true

    joy_topic: /joy
    cmd_vel_topic: /cmd_vel_joy

    # Axis mapping (note: this is a nested dictionary)
    axis_linear:
      x: 1
    axis_angular:
      yaw: 3

    # Scaling factors (also structured per axis)
    scale_linear:
      x: 0.8
    scale_linear_turbo:
      x: 1.2
    scale_angular:
      yaw: 1.2
    scale_angular_turbo:
      yaw: 2.0

    # Trigger buttons
    enable_button: 4          # LB
    enable_turbo_button: 5    # RB
    require_enable_button: true
