twist_mux:
  ros__parameters:
    use_sim_time: true
    topics:
      - name: cmd_nav
        topic: /cmd_vel_nav
        timeout: 0.5
        priority: 50
        short_desc: "Nav2 输出"

      - name: cmd_joy
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 100
        short_desc: "手柄 teleop_twist_joy 输出"

    locks:
      - name: e_stop
        topic: /emergency_stop
        timeout: 0.0
        priority: 255
        short_desc: "急停锁，非空触发"
