twist_mux:
  ros__parameters:
    use_sim_time: true

    topics:
      cmd_nav:               # <- 任意键名即可，用来标识来源
        topic: /cmd_vel_nav
        timeout: 0.5
        priority: 50
        short_desc: "Nav2 输出"

      cmd_joy:
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 100
        short_desc: "手柄 teleop_twist_joy 输出"

    locks:
      e_stop:
        topic: /emergency_stop
        timeout: 0.0         # 0 表示“非空即锁”
        priority: 255
        short_desc: "急停锁，非空触发"
